### PR TITLE
Remove old Node versions no longer supported by Github actions

### PR DESCRIPTION
**Pull request by spmiller**
https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

Removing support for these older versions (everything below 16) ensures a successful build.

### CODE REVIEW

**Comment by spmiller** [comment]
Hi @paulrutter, hopefully you can squash all those commits when you merge, it's a bit embarrassing how many it took to get right since I couldn't test locally.

**Comment by paulrutter** [comment]
Thanks, i will take a look!

**Comment by paulrutter** [comment]
Didn't manage to squash, bit i did merge the changes and added 20.x to it as well.
Let's see if it works now.

**Comment by paulrutter** [comment]
No luck yet, see https://github.com/blueconic/node-oom-heapdump/actions/runs/6650420876

**Comment by spmiller** [comment]
Looks like an error in the 20.x branch you added. Perhaps the API is different in v20?

```
../lib/node_oom_heapdump_native.cc:91:31: error: invalid conversion from ‘void (*)(const char*, bool)’ to ‘v8::OOMErrorCallback’ {aka ‘void (*)(const char*, const v8::OOMDetails&)’} [-fpermissive]
```

**Comment by paulrutter** [comment]
I will remove 20.x for now and try again.

**Comment by paulrutter** [comment]
https://github.com/blueconic/node-oom-heapdump/actions/runs/6651842671

**Comment by paulrutter** [comment]
I will investigate Node20 later, probably something needs to be added in the code itself first.

**Comment by paulrutter** [comment]
I fixed node20 support and added it to to Github actions: https://github.com/blueconic/node-oom-heapdump/actions/runs/6664282388

**Comment by spmiller** [comment]
Nice one!

**Pull request merged**
