### PR TITLE
Fix recursion issue

### PR DESCRIPTION
**Pull request by simon-abbott**
Creating a heapdump [forces a garbage collection](https://github.com/v8/v8/blob/ee74e718339223345b42935e9f4cbc7be208e557/src/profiler/heap-snapshot-generator.cc#L2228) which can then trigger the OOM flow which then calls `OnOOMError` which then creates a heapdump which then forces GC which then triggers the OOM flow which...

This recursive loop is bad for several reasons, not the least of which being if addTimestamp is true it will keep appending the timestamp to the filename, even past the end of the allotted 256 chars. This PR solves this in two parts:

1. Temporarily raise the limit while capturing the heapdump, so the GC logic thinks there is enough room.
2. Fatal error if `OnOOMError` is called more than once, just in case #1 didn't work.

### CODE REVIEW

**Comment by paulrutter** [comment]
Thanks for the PR, i missed it apparently.
I'm busy with removing the native code altogether in a new version, as Node offers out of the box tooling to create heapdumps on OoM since node 14.x.

So not sure what to do with this PR. Any ideas?
I would suggest looking into the native functionality in Node if you're using Node > 14 .

**Comment by paulrutter** [comment]
@simon-abbott i tried your PR out, and it works perfect on Node 16.
Even though there is native support in Node nowadays, it might be good to just have a working version of this module for Node 14-16 as well.

I'll work on it some work (i want to update some deprecated libraries) and that works out, i'll publish a new version to NPM.

**Comment by paulrutter** [comment]
@simon-abbott i published a new (tagged alpha) version 3.0.0 here: https://www.npmjs.com/package/node-oom-heapdump/v/3.0.0. You can test with by using `npm install node-oom-heapdump@alpha --save`.

I'm gonna test a bit more myself and also https://github.com/blueconic/node-oom-heapdump/issues/22 need to be fixed still.
If that's all ok, i can publish 3.0.0 as "latest".

**Comment by simon-abbott** [comment]
@paulrutter 

> Node offers out of the box tooling to create heapdumps on OoM since node 14.x.

Yes it technically does, but when I was testing it last it didn't work as well as I needed it to. I don't remember the exact problem(s) I ran into, but it definitely didn't check all the boxes for my use-case. This package does, however, so I'm glad to see it's still being at least lightly maintained.

**Pull request merged**
